### ISSUE TITLE
Hosts file Format

### ISSUE THREAD

**Issue by Darryl-G** [Azure/Azure-Monitor-for-SAP-solutions-preview#10]
Hello,

For name resolution we have to provide a hosts file (or rather, the content of a hosts file).
The AMS documentation states that the format should be:

`[IP]  [hostname] [fqdn]`

This is not the "standard" format for operating systems such as SUSE Linux, RHEL or IBM AIX.
Instead, it is probably much easier for the Linux and Unix community to use existing hosts file contents (copy & paste), if the format is:

`[IP]  [fqdn] [hostname]`

See:
https://documentation.suse.com/es-es/sles/15-SP1/html/SLES-all/cha-network.html#sec-network-manconf-hosts
https://www.ibm.com/docs/en/aix/7.2?topic=formats-hosts-file-format-tcpip
https://access.redhat.com/solutions/81123

Darryl

**Comment by MightySuz** [comment]
Hi Darryl, 

Thanks for pointing it out. entries will work even if you provide data in [IP] [fqdn] [hostname] format. we are working to update our messaging for this field.

**Comment by devanshjainms** [comment]
Hi, this issue has been addressed and deployed in production.
