### ISSUE TITLE
Confusing UI presentation of 'Route All' option

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#11]
Hi team,

On the Basics tab of the creation screen, the wording of the 'Route All' option in the UI could be improved in several ways: 

- Update grammar and spelling. There is some rough grammar here, and lack of capitalisation in a number of places, e.g. : 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1378845/162726955-b8c5188d-7301-4b64-ae5e-deedc866ffe4.png">

- Rephrase the option altogether. "Route All" is not a particularly great name; it's not clear whether the routing for the whole VNet is being updated, or whether it just affects the subnet for AMS2.0. I think it would be simpler if you rephrased this entire option to something like "Is direct internet access allowed from this networking segment", and then have a yes/no toggle for that. The current approach of an info message advising the user to de-select an option which is on by default makes it seem "scary".

**Comment by sameeksha91** [comment]
Hello, thank you for that feedback. We have reviewed this and suggested improvement on text. Once the fix goes live, will share with you.
