### ISSUE TITLE
Creation of NetWeaver provider failed with error SoapAPIValidationFailed

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#12]
Hi team,

I'm trying to set up a NetWeaver provider for an S/4HANA 2021 system. This is a single-VM install with all NetWeaver components on the same VM as HANA. The system and the subnet used for AMS are all part of the same VNet. Outbound internet access is open, and NSGs allow access to and from the VirtualNetwork tag. 

The services were enabled, and the system restarted. 

The test steps via the PS script return successfully: 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1378845/162742491-8e1d5707-ffce-4dda-a984-dafaa558b96b.png">
(This is being run from a jump host with VPN access to the VNet that hosts both the SAP system and the AMS resources)

Yet creation of a provider fails: 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1378845/162743932-accdfa06-61e1-456d-83aa-bc473f234a4d.png">

These were the inputs on the creation page: 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1378845/162743152-9af6b59c-9149-46d6-84af-66ec345242b3.png">

For reference:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/1378845/162743505-b8a211eb-1949-4798-8f15-d78bb9420ecb.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1378845/162743648-a9f492ac-b5cd-4efb-bf80-9977c2348317.png">

It would be really great if the raw error from the script could be shown in the portal to help with troubleshooting :-) 
Hoping you can help with this. I'm in Singapore (UTC+8) if you would like to jump onto a call.

**Comment by hsridharan** [comment]
Hello @sufw,

We checked the logs and everything looks fine at our end. There is some networking-related issue where we are not able to make a connection to your SAP VM from the Azure portal.
Can you please share the result of the PowerShell script with the following change:
$Function = "GetSystemInstanceList"
Also can you please check if the port 50013 and 50014 is not blocked in the SAP VM - labs4hhdb2021. You can open the port in Linux using the following commands : 
--Open a port Linux
sudo firewall-cmd --permanent --zone=public --add-port=50013/tcp
sudo firewall-cmd --reload

sudo firewall-cmd --permanent --zone=public --add-port=50014/tcp
sudo firewall-cmd --reload
It will be great if you could share the Email to share the meeting invite if the above steps still do not help you out.

Thanks,
Harsha

**Comment by sufw** [comment]
Hi Harsha,

Seems the root cause is operator error... The Azure Monitor subnet I used was in a different VNet from the SAP system I was trying to monitor. Both were peered to the same hub VNet, and while NSGs permitted access, transit routing was not enabled hence there was no route from Azure Monitor to the SAP system... :-|

I have re-created the AMS instance in the same VNet as the SAP system I'm trying to monitor, and now the creation of the Netweaver provider was successful. 

Sorry about this. However it would be great if more detailed error messages could be surfaced to the user, including the raw error from the underlying tool. This might have given a hint about the root cause and sped up resolution. 

Sascha

**Comment by hsridharan** [comment]
Hello @sufw,

This is great feedback. Let me take this to our PM team and see if there is a way we can show these backend errors on the portal UI.
I am happy you were able to identify and resolve the same.

Thanks,
Harsha
