### ISSUE TITLE
Feature request: provide detailed/raw error messages from provider setup

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#13]
Hi team, 

To help speed up the troubleshooting of connection and permission issues during provider setup, it would be great if the raw error message from the underlying tool could be surfaced into the portal. Please see issue #12 as an example. The root cause was missing transit routing across a Hub network, but the generic error message resulted in a few hours of troubleshooting. 

Sascha

**Comment by archanak-msft** [comment]
Acknowledge this request. Adding @MightySuz and @sameeksha91 for further action.
