### ISSUE TITLE
Error code 'sapHanaConnectionFailed' when setting up a HANA provider

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#14]
Hi team, 
Creation of a HANA provider fails with the following error: 

```
{"code":"ProviderInstanceValidationOperationFailed","message":"
The provider settings validation operation has failed with code 'sapHanaConnectionFailed'.
Possible Causes: The operation failed with error: 'Connection to SAP HANA Failed.'.
Recommended Action: 'Please Update connection settings.'.
","details":[]}
```

This is not the same root cause as for Issue #12. The NetWeaver and Linux providers for the same VM are created successfully: 
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1378845/162907394-04088461-8046-4541-8c20-2faae4296987.png">

I have tried three different setups against the SYSTEMDB, none of which appear to connect: 
- dedicated AZUREMONITOR user with the MONITORING role and CATALOG READ system privilege with IP address
- the SYSTEM user with IP address
- the AZUREMONITOR user with FQDN

The FQDN (labs4hhdb2021.sap-internal.softwareone.cloud) is in a public zone and returns the internal IP of the host. 
HANA Studio is able to connect with the dedicated user, so the password works. 
It might be relevant that the SSL certificate in the HANA system is self-signed, and the connection from HANA Studio only succeeds if 'Validate the SSL certificate' is unticked. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1378845/162907944-b8956ffd-6159-4400-bf40-93270ee6f779.png">

There are no firewalls active on the host: 
![image](https://user-images.githubusercontent.com/1378845/162909207-52ed4f18-cc0a-494f-b8c9-92f561bd87aa.png)

This is an MDC system with instance number 21. Port 32115 is reachable from an external machine: 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1378845/162909427-da8f0992-2957-4289-a334-f6d068b1d493.png">

As per #13 it would be really useful to see detailed error messages to troubleshoot this. 

Sascha

**Comment by NeenuVincent** [comment]
Hi, 

Usually, the systemdb port is 3xx13. What we noticed here is port number given is 3xx15. Can you please try creating a HANA provider by giving port number 3<instance number>13? If the issue still persists, then we can have a quick call.

Thank you.
Neenu

**Comment by sufw** [comment]
Hi Neenu,

Thank you for the tip - that worked. I was a bit thrown off by the comment in the portal that port 3xx15 should be used for MDC systems. This is also the port that HANA Studio appeared to be connecting to. 

Might be worthwhile updating the text of the tooltip? 

![image](https://user-images.githubusercontent.com/1378845/163287887-33c23cd2-bb2b-43a5-ae71-3237faae353c.png)
