### ISSUE TITLE
Feature request: HANA provider should run MiniChecks daily

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#15]
The HANA MiniChecks provide a lot of useful information on the health of a HANA system, and it's especially interesting to observe the values of certain parameters over time - an ideal use case for AMS2.0. 

The HANA connector should execute the MiniCheck statements (file HANA_ABAP_MiniChecks.txt inside the ZIP file attached to SAP Note 1969700) on a periodic basis (hourly or daily), so that results are available for reporting.

**Comment by archanak-msft** [comment]
Acknowledging this. Adding @sameeksha91 for further action.
@MightySuz  as FYI.

**Comment by MightySuz** [comment]
Hi @sufw , thanks for the feedback. We have added this to our product backlog and will work on it based on further customer interests and priorities.
