### ISSUE TITLE
HANA Provider deployment failed with InstanceInitializationFailed error 

### ISSUE THREAD

**Issue by akrutikov98** [Azure/Azure-Monitor-for-SAP-solutions-preview#16]
Hello,

HANA Provide deployment failed shortly after start. In the extended log, the following explanation can be found:

The instance initialization operation failed.
      Possible Causes: The operation failed due to an internal error.
      Recommended Action: Retry the operation. If the issue persists, please create an issue here :- https://aka.ms/AAgc4fy.
     (Code: InstanceInitializationFailed)

We're in East US 2 region, subscription id is 2fb5284c-8225-4328-8a84-602f9355da07.

Thanks,
Aleksey

**Comment by NeenuVincent** [comment]
Hi Aleksey,

Thank you for reaching out to us. We will look into this issue. Did you try creating HANA provider again? Is it happening the next time also?

Regards,
Neenu Vincent

**Comment by akrutikov98** [comment]
Hi Neenu,

Yes I tried it several times with the same result.

Thanks,
Aleksey

**Comment by NeenuVincent** [comment]
Hi Aleksey,

This issue is not reproducible at our end. It would be great if you can share your email id for us to set up a call with you. Please do share the suitable time to set up the meeting as well. This would help us understand the issue more and resolve it quickly.

Thank you.
Regards,
Neenu Vincent

**Comment by akrutikov98** [comment]
Hello Neenu,

Email id is aleksey@protera.com, I'm located in the US CST time zone and typically available during normal US business hours.

Regards,
Aleksey

**Comment by NeenuVincent** [comment]
Hi Aleksey,

Thank you for the details. We have set up a meeting. Let's discuss this in detail in the meeting.

Regards,
Neenu Vincent
