### ISSUE TITLE
Unable to create HANA provider

### ISSUE THREAD

**Issue by ramuwelcome123** [Azure/Azure-Monitor-for-SAP-solutions-preview#21]
Failed to create provider HQ1-HDB3 for sqatams01. Error: 
      The instance initialization operation failed.
      Possible Causes: The operation failed due to an internal error.
      Recommended Action: Retry the operation. If the issue persists, please create an issue here :- https://aka.ms/AAgc4fy.
and could not execute SQL with exception (260, 'invalid column name: INITIATION: line 1 col 9787 (at pos 9786)')

**Comment by lharcekova** [comment]
Hi,

Thank you for reaching out to us. After investigation of this issue, we find out you are using HANA 1.0, which is currently out of support from SAP itself, and AMS 2.0 will not support it as well.

![image](https://user-images.githubusercontent.com/98498799/166107097-b17d69d3-b35e-4d57-b3ad-116d68e46f9c.png)

Please let us know if you have any further questions that we may help you with.

Regards,
Lucia Harcekova

**Comment by nitinagg1** [comment]
Hi @ramuwelcome123 can you also delete the monitor created. This will save you cost of the resources created.
In case of issues, feel free to reach out to us.

Thanks
Nitin
