### ISSUE TITLE
eastus2 region required for AMS deployment

### ISSUE THREAD

**Issue by mkerni** [Azure/Azure-Monitor-for-SAP-solutions-preview#22]
As part of the ASM deployment, I had some issue to deploy it into eastus. I was getting following error
![image](https://user-images.githubusercontent.com/97944773/167127493-9960c76e-55b2-4dde-b82e-838046a7a419.png)

After some troubleshooting, I realized that the error is related to our policy which (intentionally) denies any deployment into eastus2 region, because when I allowed eastus2 for deployment the error was gone. It seems the deployment template has some hardcoded parameter with value eastus2! See my following suspicious findings:

1. The deployment template contains the eastus2 in parameter "Location" ![image](https://user-images.githubusercontent.com/97944773/167125537-1912320b-9aa5-411e-b888-f11b9de7fc33.png)

2. Deployed AMS resource contains in properties parameter "Service Location" values with "East US 2"  ![image](https://user-images.githubusercontent.com/97944773/167126995-bf1ddf17-6da6-4b35-b708-6fcc48552b65.png)

3. The ASM was deployed correctly to eastus alongside with all related resources
![image](https://user-images.githubusercontent.com/97944773/167126662-c6bf4716-0c8c-4c51-b80b-ee9f85dcd997.png)
![image](https://user-images.githubusercontent.com/97944773/167126449-cf211d24-3133-4fbc-abf8-5d4e3def8b3d.png)
 
Kindly fix dependency on eastus2 to ensure all AMS resources are deployed into selected region as part of the ASM deployment.

**Comment by archanak-msft** [comment]
@MightySuz  and @sameeksha91

**Comment by ezequielmqg** [comment]
i hava the same problem. I only want to deploy in EastUS, but some resources ends up being located in EastUS2.

**Comment by MightySuz** [comment]
Hi @mkerni  and @ezequielmqg , thanks for reporting this behavior. AMS is currently using Geo based deployment method, where AMS service is hosted in one region in a geography (EastUS2) but AMS resource can be setup in another region within that geography. We are planning to have AMS service available in all the supported regions by GA. 

For now, you will need to update your azure policy to allow few resources to be created in a different region than your SAP system. Please note that these resources are only for tracking purposes and not have any bearing on performance of AMS.

**Comment by MightySuz** [comment]
Please let me know if it's ok to close this issue. Thanks

**Comment by mkerni** [comment]
Yes, this limitation make sense for the preview phase but should be addressed when going for GA.
With temporary enabled region EastUS2 in the policy template I can deploy the AMS into the EastUS region.
I'm ok to close this issue.
