### ISSUE TITLE
HAHA provider failed - Authentication error

### ISSUE THREAD

**Issue by sangharsh-dongre-vivint-com** [Azure/Azure-Monitor-for-SAP-solutions-preview#23]
Failed to create provider ECD for azuremonitorV2. Error: The provider settings validation operation has failed with code 'SapHanaAuthenticationFailed'. Possible Causes: The operation failed with error: 'Authentication failed, given database username or password is wrong.'. Recommended Action: 'Please check if the given username and password details are correct.'.

**Comment by devanshjainms** [comment]
@sangharsh-dongre-vivint-com 

Can you please try creating the HANA provider with correct username and password? Please let me know if you are still having this issue even after entering the correct credentials. Thanks.

**Comment by devanshjainms** [comment]
Update: This issue is resolved and Sangharsh was able to add the HANA provider successfully. Additionally, we observed there is an issue with HANA Alerts check we are running. This hotfix is ready, and this incident is kept open to track that issue.
