### ISSUE TITLE
Need to understand the Data Size prediction charts in SAP Hana dashboard for AMS2.0

### ISSUE THREAD

**Issue by aggVishal** [Azure/Azure-Monitor-for-SAP-solutions-preview#26]
I have configured the AMS SAP Hana provider and I am getting the data for all the tabs in the SAP Hana dashboard, but I need to understand the prediction charts in data size. Also, I need to understand the algorithm you guys are using to calculate this prediction. I need to understand all the terms mentioned in these 2 charts.

![image](https://user-images.githubusercontent.com/65781736/172380637-3f5fe0e9-e145-4b9d-aa45-8e38f035c3af.png)

**Comment by aggVishal** [comment]
Any update on this issue?

**Comment by lharcekova** [comment]
Hi Ahh,

thank you for your patience.

The left graph is for columns and the right one is for total memory.
The input parameters can be adjusted to create a capacity prediction scenario that best suits your HANA environment. Click on the "i" symbol to see an explanation for each parameter.

The high level of the algorithm:
First, the global allocation limit is calculated
Then memory used over time is calculated to create the slope
Then Column store over time is calculated with slope over time
This is all then displayed in the graph below.

If you have any follow-up questions please let us know.

Best regards,
Harcekova Lucia

**Comment by aggVishal** [comment]
Thanks, @lharcekova for this, but I need a more detailed explanation of how these algorithms are designed, on which factors you are calculating these predictions, etc. Everything in and out on  these two charts.

Please help me with this!

Thanks for replying,
Vishal Aggarwal

**Comment by lharcekova** [comment]
Hi Vishal,

Happy to help.

You can access the code and all specific algorithms for every part in the workbook code by clicking on the edit button: 
![image](https://user-images.githubusercontent.com/98498799/173393797-85b99091-df03-47b4-8d46-952e23100926.png)
![image](https://user-images.githubusercontent.com/98498799/173402349-62d7902e-2e71-4515-b32a-7a83a3ee94cb.png)


The code is as well shared within Github:  https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Workbooks/SapMonitor2.0/SapHana/SapHana.workbook

This is the code for the Data size tab for the first graph:
let daysintimeframe={param_timeframe:seconds}/60/60/24;
let chosendatalimit=todouble(param_percentofgal_handled)*todouble(param_gal_handled)/100;
let series_csdatasize_nopad=myparambag.series_datasize;
let intercept=todouble(myparambag.datasize_interception)+offset;
let timestamps=myparambag.array_allthedays ;
let firstpos=toint(myparambag.datasize_firstpos);
let lastpos=daysintimeframe-firstpos;
let leadingnulls=repeat(long(null),daysintimeframe );
// Make the bestfit line based on the slope and intercept
let predfirstdate=todatetime(myparambag.datasize_firstdate);
let gap=chosendatalimit - intercept;
let daystofull_uncapped=toint(bin(gap/slope,1));
let daystofull=min_of(daystofull_uncapped,toint(datetime_diff('day',now(183d),predfirstdate)));
let systemfulldate=datetime_add('day',daystofull,predfirstdate);
let lastdatetoplot=todatetime(timestamps[array_length(timestamps) -1]);
let datestoaddd=range(datetime_add('day',1,lastdatetoplot), systemfulldate, 1d);
let sampledates=array_concat(timestamps,datestoaddd);
// Create lists as long as the prediction
let series_gal=repeat(todouble(param_gal_handled),array_length(sampledates));
let series_chosendatalimit=repeat(chosendatalimit,array_length(sampledates));
let rpadding=repeat(long(null), array_length(datestoaddd));
let series_csdatasize=array_concat(series_csdatasize_nopad,rpadding);
let plotfrom=daysintimeframe-firstpos;

//print firstpos, daystofull, plotfrom, daysintimeframe
//create prediction line and plot others against it
range x from lastpos to daystofull step 1
| project bestfit=slope*x+intercept
| summarize make_list(bestfit)
| project 
    sampledates,
    ColumnDataSize=series_csdatasize, 
    ColumnDataPrediction=array_concat(leadingnulls,list_bestfit),
    GlobalAllocationLimit=series_gal, 
    PredictionLimitLine=series_chosendatalimit

You can see all the others directly in your workbook or on the Github page.

Have a great day.

Best regards,
Harcekova Lucia

**Comment by aggVishal** [comment]
Thanks, @lharcekova for this, I didn't know about this. But when I clicked on the Edit button on top, I still can't see the edit buttons on these two charts, I can just see the edit buttons for other filters on top.

![image](https://user-images.githubusercontent.com/65781736/173576613-77ed92fd-c9c8-41a7-92d9-287f1cbbd9a8.png)

![image](https://user-images.githubusercontent.com/65781736/173576682-d13f1153-dc85-4989-8577-bda2e2e784e1.png)

Please help me with this!

Thanks,
Vishal Aggarwal

**Comment by lharcekova** [comment]
Hi Vishal,

in the beginning, you need to go through 2 more Edits always located under the section.
There is the hierarchy of elements and these graphs are nested in the lowest layer. That's the reason why you need to click a few times "Edit" below the section to actually get inside the specific graph.

![image](https://user-images.githubusercontent.com/98498799/173640647-140fc043-98d9-4e45-bd94-b7551e88156b.png)

![image](https://user-images.githubusercontent.com/98498799/173640751-c19d347f-bf4f-4e60-88e7-4d293e54ecec.png)

![image](https://user-images.githubusercontent.com/98498799/173640854-ab3f02e5-97cb-44e5-bcb1-935920d0791f.png)

Kind regards,
Harcekova Lucia
