### ISSUE TITLE
Error in Process Utilisation view

### ISSUE THREAD

**Issue by sufw** [Azure/Azure-Monitor-for-SAP-solutions-preview#31]
Hi team,

I have a system with 12 DIA and 8 BTC work processes: 

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/1378845/173863738-e8ef0e82-e633-422c-a3ee-46238b8340e2.png">

However the Process Utilisation view incorrectly shows 12 Available WPs of type "Any": 

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/1378845/173863254-28f1f154-4eff-4e6a-bf59-460802139faf.png">

When I change to filter to "BTC", I correctly see 8 available WPs, which matches the system's configuration. Similarly when explicitly selecting DIA, I see 12, which is correct. However "Any" should display a total of 23. 

Sascha

**Comment by hsridharan** [comment]
Hello @sufw ,

In the workbook, in general - "Any" means anyone from the list and by default, it picks up the first one in the list which must be "DIA" and hence it's showing up as "12". Here "Any" does not mean the total number of WPs.
I am happy to assist you if you have any additional questions regarding the same.

Thanks,
Harsha

**Comment by sufw** [comment]
Hi Harsha,

Be that as it may, the end result is not what one would expect, and I would say even misleading. 
Usually the DIA and BTC process utilisation are the most interesting metrics. It would make sense to show the utilisation of these two over time as a % of the configured total. Right now this visualisation is misleading if "Any" means "first in the list". 

Sascha
