### ISSUE TITLE
 while adding provider for SAP net Viewer we are getting the below error

### ISSUE THREAD

**Issue by Abhay-Anand149** [Azure/Azure-Monitor-for-SAP-solutions-preview#36]
@ad-gitman 
{"code":"ProviderInstanceValidationOperationFailed","message":"\n The provider settings validation operation has failed with code 'SoapAPIValidationFailed'.\n Possible Causes: The operation failed with error: 'Unable to reach the hostname: xx.xxx.xxx.xxx. Error occurred while validating SOAP client API calls for SAP system.'.\n Recommended Action: 'Please check the input hostname, instance number, and host file entries. Ensure that the SOAP web service methods are unprotected correctly.'.\n ","details":[]}

**Comment by hsridharan** [comment]
Hello @Abhay-Anand149 ,

Can you please confirm the host file entries you provided for all the central instances, application servers, and replication servers (if any) in the specified format?
Also kindly share your subscription id, so that we can take a look at the detailed logs.

Thanks,
Harsha

**Comment by devanshjainms** [comment]
Hi @Abhay-Anand149, were you able to add the NetWeaver provider?

**Comment by lharcekova** [comment]
Hi @Abhay-Anand149,

please let me know if you require any further assistance from our side. We will be closing this ticket for now.

Best regards,
Harcekova Lucia
