### ISSUE TITLE
Problem in create provider for SAP SolMan Java

### ISSUE THREAD

**Issue by antsetia** [Azure/Azure-Monitor-for-SAP-solutions-preview#37]
Hi Team,

I have 2 cases related with SAP Java System, one is successfull, and the other one is failed.

1. Create provider for SAP PO (Java), LINUX Based **successful**

We configure in SAP JAVA DEFAULT.PFL Profile:
service/protectedwebmethods = SDEFAULT -GetQueueStatistic -ABAPGetWPTable -EnqGetStatistic -GetProcessList

dp7adm> sapcontrol -nr 00 -function ParameterValue service/protectedwebmethods

24.06.2022 03:02:53
ParameterValue
OK

SDEFAULT -GetQueueStatistic -ABAPGetWPTable -EnqGetStatistic -GetProcessList

We filled below information during provider creation
SID: is filled by SAP Java SID
Application Server: is the hostname FQDN
Instance Number: is filled by SAP Java instance number
Connection type: SOAP(HTTP)
Hostfile entries: <IP> <hostname> <FQDN>

2. Create provider for SAP SolMan (Java) Windows Based **failed**

In this case, **we have 2 SAP instance SolMan in one server.** 
First is SolMan ABAP instance (which the created provider is success), and the other instance is SAP SolMan JAVA instance, which is failed to created provider with below error:

Failed to update provider
Failed to update provider SolManJAVA for usw3-saplab-azmonitor. Error: 
      The provider settings validation operation has failed with code 'SoapAPIValidationFailed'.
      Possible Causes: The operation failed with error: 'Unable to reach the hostname: devlabsmapp.sap-internal.softwareone.cloud. Error occurred while validating SOAP client API calls for SAP system.'.
      Recommended Action: 'Please check the input hostname, instance number, and host file entries. Ensure that the SOAP web service methods are unprotected correctly.'.

We already setup the parameter into SAP SolMan JAVA, and tried created provider with parameter like case no. 1
service/protectedwebmethods = SDEFAULT -GetQueueStatistic -ABAPGetWPTable -EnqGetStatistic -GetProcessList

C:\Users\sj7adm>sapcontrol -nr 02 -function ParameterValue service/protectedwebmethods

24.06.2022 03:07:41
ParameterValue
FAIL: HTTP Error, HTTP/1.1 401 Unauthorized

![Failed created provider 2](https://user-images.githubusercontent.com/107845418/175456639-75d0eff3-e04f-486a-a119-5a46d7f58f5e.jpg)
![Check protectedwebmethods](https://user-images.githubusercontent.com/107845418/175454588-fd74948a-5e63-45ed-a2aa-f9b4302c5962.jpg)

**Comment by hsridharan** [comment]
Hello @antsetia ,

Did u restart the instance service using the below command in the system -  SAP SolMan JAVA after updating up SDEFAULT profile parameter?

Execute the command to restart the instance service –
/usr/sap/hostctrl/exe/sapcontrol -nr <instanceNumber> -function RestartService

Execute the command to test – whether the unprotect worked 
/usr/sap/hostctrl/exe/sapcontrol -nr <instanceNumber> -function ParameterValue 
service/protectedwebmethods

. Execute PowerShell command to test whether unprotection truly worked ( use it from your local 
system ). Please replace hostname and instancenumber.

$SAPHostName = **"<hostname>"**
$InstanceNumber = **"<instancenumber>"**
$Function = " GetSystemInstanceList"
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
$sapcntrluri = "https://" + $SAPHostName + ":5" + $InstanceNumber + "14/?wsdl"
$sapcntrl = New-WebServiceProxy -uri $sapcntrluri -namespace WebServiceProxy -class sapcntrl
$FunctionObject = New-Object ($sapcntrl.GetType().NameSpace + ".$Function")
$sapcntrl.$Function($FunctionObject)

If all the above steps are successful. Please try to recreate the provider and kindly share the subscription id if its failes again.

Thanks,
Harsha

**Comment by antsetia** [comment]
Hi Harsa,

As informed, this solman system is build in windows OS, and we have 2 instances in this server, Solman ABAP and Solman Java,

So, We are restarting use below way:

![image](https://user-images.githubusercontent.com/107845418/177248905-d243c967-483d-451f-a7b7-8853a78e5097.png)

and even, we already stop the VM in last weekend, and start in this monday.
I tried your suggested way with below result.

![image](https://user-images.githubusercontent.com/107845418/177249127-e10e71cc-050b-4ddb-9011-bc5abe2c67cb.png)

I believe it is happen because we have 2 instances in the same server.

For Powershell script,
I tested to Solman **ABAP**, and it works

![image](https://user-images.githubusercontent.com/107845418/177249455-6e0be835-e521-459a-80ab-8c44d349e7dd.png)


But for Solman **JAVA** (in the same sever but different instance number), it is failed

![image](https://user-images.githubusercontent.com/107845418/177249564-373975a8-2440-4137-910b-54394a776602.png)

Regards,
Anton

**Comment by hsridharan** [comment]
Hello @antsetia,

Can you please try restarting the service in MMC using "Restart Service" because I see "401 unauthorized" exception on your screenshot?

![image](https://user-images.githubusercontent.com/74435183/177266119-1f2bd0a3-d165-4bd9-82b9-58bcabc9768c.png)

Can you share your timezone and email, we would like to connect with you over teams call and resolve all your issues.

Thanks,
Harsha

**Comment by antsetia** [comment]
Hi Harsha,

My email is: anton.setiawan@softwareone.com
My timezone is UTC + 7

I have restarted the Java application services as you advise, but the result is still Unauthorized.

![image](https://user-images.githubusercontent.com/107845418/177896282-e0d25acd-8009-4bc5-ab5b-752d1c36bdc5.png)

![image](https://user-images.githubusercontent.com/107845418/177896321-467b2d48-9d14-4d19-8d1f-983e6131154a.png)

Regards,
Anton

**Comment by hsridharan** [comment]
Hello Anton,

Can you please try login as the service user which is used during installation and then running this command? 
When you to go services, SAPHostControl service right click and you will see user Id responsible for it.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/74435183/180580457-f71bd322-4ecb-4772-a1e4-0fb5aa0bf56b.png">

Please check and let us know if this worked for you. 
Otherwise, we can connect on Teams to troubleshoot this further.

Thanks,
Harsha

**Comment by antsetia** [comment]
Hi Harsha,

I've just check that the SAPHostControl service and the user ID responsible already sapadm since the installation complete, and the problem still exist.

![image](https://user-images.githubusercontent.com/107845418/180680508-51fc4166-cae4-4d1b-82f5-358135394a89.png)

I can join team meeting as scheduled.

Regards,
Anton Setiawan

**Comment by hsridharan** [comment]
Hello Anton,

I hope we resolved all the issues in SolManJAVA provider in yesterday's call. I am closing this ticket for now.

Thanks,
Harsha
