### ISSUE TITLE
Lock Entries (SM12) is not displayed in azure monitor

### ISSUE THREAD

**Issue by antsetia** [Azure/Azure-Monitor-for-SAP-solutions-preview#38]
Hi Team,

We have lock entries in SAP System (Tcode SM12), but it is not displayed in azure monitor, as shown in screenshot

There is also an information in azure monitor that advise to set parameter: time_sm12.
Please advise, how we set this parameter ?

![image](https://user-images.githubusercontent.com/107845418/175470367-ddaf40bd-b588-4f66-b05f-4f73960037f1.png)
![image](https://user-images.githubusercontent.com/107845418/175470416-a83ceecd-4e42-49b6-a11c-ef1adc65ee5f.png)

**Comment by antsetia** [comment]
Hi Harsha,

Below are the result:

![image](https://user-images.githubusercontent.com/107845418/177233240-a0bf4c71-5743-452d-a059-0ddee21ce3d3.png)

![image](https://user-images.githubusercontent.com/107845418/177233298-7d2d6de6-c41d-40b1-8230-14bdbdf95152.png)

![image](https://user-images.githubusercontent.com/107845418/177233321-5619993c-df02-4798-bc6b-a3443977051b.png)

eventhough the there is 3 entries on SM12, but from function module ENQUEUE_READ only show 1 module.

The role has been assigned as instruction (by uploaded provided roles and generated the roles)

![image](https://user-images.githubusercontent.com/107845418/177233583-15e4c31b-3dd3-4549-901f-7866024638ab.png)

![image](https://user-images.githubusercontent.com/107845418/177233662-31b3fa32-7f14-4f0d-b1b1-129c35595795.png)

Regards,
Anton

**Comment by hsridharan** [comment]
Hello @antsetia ,

Thanks for sharing the screenshots. Do you mean to say that its working as expected now? I can see the Lock entries populated in your workbook.

Thanks,
Harsha

**Comment by antsetia** [comment]
Hi Harsa,

Yes, it looks good. We can close this ticket.
