### ISSUE TITLE
: ERROR: The input payload failed during the validation  ( creating  Infrastructure  ) 

### ISSUE THREAD

**Issue by RobertaSune** [Azure/Azure-Monitor-for-SAP-solutions-preview#4]
hello

I have a error  during  step 4.1 Creating Infrastructure Deployment. I tried to deploy  few times with different sizes, regions and architecture but the issues is always the same.

thanks in advance.
Roberta.
 
![image1](https://user-images.githubusercontent.com/99688118/158805109-c1e141e1-1946-4035-8ceb-161e25facb3b.jpg)
![image2](https://user-images.githubusercontent.com/99688118/158805116-150e8822-d97a-49bb-9681-b2b1745d884f.jpg)
![image3](https://user-images.githubusercontent.com/99688118/158805117-214033cd-0f24-43dd-8bf5-b9b18a024795.jpg)

**Comment by kalyaninamuduri** [comment]
This is ACSS issue logged incorrectly in AMS repo. The issue for the user has been resolved separately and this can be closed.
