### ISSUE TITLE
AMS (preview) support for SAP AS JAVA, SAP ASE and WebDispatcher

### ISSUE THREAD

**Issue by yoganandv** [Azure/Azure-Monitor-for-SAP-solutions-preview#43]
Hello team,

Does the AMS (preview) support the addition of SAP AS JAVA stack, SAP ASE and SAP WebDispatcher nodes?

I remember SAP AS JAVA was not supported initially, has anything changed now?

Thanks.

Regards,
Yoganand.V

**Comment by MightySuz** [comment]
Hi Yoganand, we are still prioritizing SAP ABAP monitoring at this point and not supporting SAP AS JAVA. We will prioritize if there is enough interest from customers on the same.
