### ISSUE TITLE
SAP NetWeaver Provider issue

### ISSUE THREAD

**Issue by Abhay-Anand149** [Azure/Azure-Monitor-for-SAP-solutions-preview#44]
Hi Team,
While adding the provider to SAP NetWeaver, we're getting the below (this is a cluster environment).
Subscription id:316a483e-ce33-4251-92f9-aaf74b6c10bd

The provider settings validation operation has failed with code 'SoapAPIValidationFailed'.
      Possible Causes: The operation failed with error: 'Unable to reach the hostname: 10.63.3.43. Error occurred while validating SOAP client API calls for SAP system.'.
      Recommended Action: 'Please check the input hostname, instance number, and host file entries. Ensure that the SOAP web service methods are unprotected correctly.'.
     (Code: ProviderInstanceValidationOperationFailed)

kindly help us how to fix the issue.

**Comment by prasoonpankaj-25** [comment]
Hello Abhay, 

Based on the error it appears that prerequisites for the provider have not been completed. We would request you enter the correct host mapping for all the application, ascs servers. Refer to the link https://github.com/Azure/Azure-Monitor-for-SAP-solutions-preview/wiki/Known-issues-and-Self-Help for more details and you can check the public documentation - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-netweaver-azure-monitor-sap-solutions . 

In case the issue still persists we recommend getting in touch with the cloud support team and raising appropriate incidents. 

Regards, 
Pankaj

**Comment by devanshjainms** [comment]
Hi @Abhay-Anand149 , did you get a chance to re-try this operation? Was it successful? Can you please share any updates that you have?

**Comment by Abhay-Anand149** [comment]
> Hi @Abhay-Anand149 , did you get a chance to re-try this operation? Was it successful? Can you please share any updates that you have?

Yes, we tried as per recommendation, but it failed .

The provider settings validation operation has failed with code 'SoapAPIValidationFailed'.
      Possible Causes: The operation failed with error: 'Unable to reach the hostname: 10.63.3.43. Error occurred while validating SOAP client API calls for SAP system.'.
      Recommended Action: 'Please check the input hostname, instance number, and host file entries. Ensure that the SOAP web service methods are unprotected correctly.'.
     (Code: ProviderInstanceValidationOperationFailed)

Could you please clarify the doubts regarding the below.

1.What should be the value for service/protectedwebmethods parameter in JAVA systems
Our SolMan is a dual stack system which ahs both ABAP and JAVA running 

2.what should be the roles assigned to database users in case of production systems

**Comment by prasoonpankaj-25** [comment]
Hello @Abhay-Anand149 , 

Thanks for reaching out, It appears from the error message you are entering an IP address and the IP is not getting resolved. Please enter the hostname of the application server (in case of multiple hosts joining Load balancer or web dispatcher, single host you can enter CI hostname ). 

also ensure you run "/usr/sap/hostctrl/exe/sapcontrol -nr <instancenumber> -function GetSystemInstanceList" , ensure all the hostname mapping are present in the configuration. 

For your two questions

1. The value are very similar only getinstancelist and processlist are usually used for JAVA system 
2. For NW system, we don't connect to DB directly its via the application layer. refer to the job aid https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-netweaver-azure-monitor-sap-solutions - section Set up RFC metrics.

In case you need any further explanation request you to get in touch with your cloud support team and they can raise an internal support ticket. 

We would be closing this request as the product is already available for public preview.

**Comment by Abhay-Anand149** [comment]
> Hello @Abhay-Anand149 ,
> 
> Thanks for reaching out, It appears from the error message you are entering an IP address and the IP is not getting resolved. Please enter the hostname of the application server (in case of multiple hosts joining Load balancer or web dispatcher, single host you can enter CI hostname ).
> 
> also ensure you run "/usr/sap/hostctrl/exe/sapcontrol -nr -function GetSystemInstanceList" , ensure all the hostname mapping are present in the configuration.
> 
> For your two questions
> 
> 1. The value are very similar only getinstancelist and processlist are usually used for JAVA system
> 2. For NW system, we don't connect to DB directly its via the application layer. refer to the job aid https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-netweaver-azure-monitor-sap-solutions - section Set up RFC metrics.
> 
> In case you need any further explanation request you to get in touch with your cloud support team and they can raise an internal support ticket.
> 
> We would be closing this request as the product is already available for public preview.


Hi Team,

We configured the SAP NetWeaver server with connect type: SOAP (HTTP) for No. 2, and it works fine for other systems, whereas the other NetWeaver system (10.63.3.43) failed, as previously shared.

Kindly suggest.

**Comment by devanshjainms** [comment]
> > Hello @Abhay-Anand149 ,
> > Thanks for reaching out, It appears from the error message you are entering an IP address and the IP is not getting resolved. Please enter the hostname of the application server (in case of multiple hosts joining Load balancer or web dispatcher, single host you can enter CI hostname ).
> > also ensure you run "/usr/sap/hostctrl/exe/sapcontrol -nr -function GetSystemInstanceList" , ensure all the hostname mapping are present in the configuration.
> > For your two questions
> > 
> > 1. The value are very similar only getinstancelist and processlist are usually used for JAVA system
> > 2. For NW system, we don't connect to DB directly its via the application layer. refer to the job aid https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-netweaver-azure-monitor-sap-solutions - section Set up RFC metrics.
> > 
> > In case you need any further explanation request you to get in touch with your cloud support team and they can raise an internal support ticket.
> > We would be closing this request as the product is already available for public preview.
> 
> Hi Team,
> 
> We configured the SAP NetWeaver server with connect type: SOAP (HTTP) for No. 2, and it works fine for other systems, whereas the other NetWeaver system (10.63.3.43) failed, as previously shared.
> 
> Kindly suggest.

Hi @Abhay-Anand149, it appears from the error message you are entering an IP address and the IP is not getting resolved. Please enter the hostname of the application server (in case of multiple hosts joining Load balancer or web dispatcher, single host you can enter CI hostname). Additionally, please make sure you provider the DNS mappings for all the application servers, central servers, replication server in the "Hostfile Entries" input field. (smp-ascs, smp-ers)
We will be closing this ticket for now, and we request you to reach out to the cloud support team via Azure Portal.

Thanks!

**Comment by devanshjainms** [comment]
Closing the issue, as no response for around 2 months.
