### ISSUE TITLE
SAP Netweaver Provider Error

### ISSUE THREAD

**Issue by naherring** [Azure/Azure-Monitor-for-SAP-solutions-preview#46]
Hello,

I am getting an error while trying to configure an SAP Netweaver Provider, as follows:
The provider settings validation operation has failed with code 'SoapAPIValidationFailed'.
      Possible Causes: The operation failed with error: 'Unable to reach the hostname: X.X.X.X. Error occurred while validating SOAP client API calls for SAP system.'.
      Recommended Action: 'Please check the input hostname, instance number, and host file entries. Ensure that the SOAP web service methods are unprotected correctly.'.
     (Code: ProviderInstanceValidationOperationFailed)

I've gone through all of the prerequisite steps. The service/protectedwebmethods parameter is successfully set for the system and the sapcontrol check of it comes back OK. However, when I run the PowerShell that is meant to be a test query, I get the following output:
Cannot convert argument "ABAPGetWPTable1", with value: "WebServiceProxy.ABAPGetWPTable", for "ABAPGetWPTable" to type
"WebServiceProxy.ABAPGetWPTable": "Cannot convert the "WebServiceProxy.ABAPGetWPTable" value of type
"WebServiceProxy.ABAPGetWPTable" to type "WebServiceProxy.ABAPGetWPTable"."
At line:1 char:1
+ $sapcntrl.$Function($FunctionObject)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

I have made sure in the Adding Netweaver Process that I have added the hostname and host file entries inputs. Any insight you have on this matter would be greatly appreciated.

Thank you in advance!

**Comment by kavitha2270** [comment]
@naherring , 
Few things to verify

-  please make sure the ports (range 50013-59916) are allowed in NSG rule.
- Test to check If ports are open by trying the wsdl in a browser.

If issue still persists, please open a support ticket with subscription id so that we can assist you further.
Thanks!

**Comment by naherring** [comment]
- please make sure the ports (range 50013-59916) are allowed in NSG rule. - _Do you mean the NSG rule associated with the subnet created for the monitoring or the one where SAP resides? It is open across the subnets for any port._ 
- Test to check If ports are open by trying the wsdl in a browser. - _I am able to successfully reach the link in a browser without issue._

**Comment by kavitha2270** [comment]
@naherring , can you please provide us the AMS name for us to trace?

**Comment by naherring** [comment]
The AMS name is s4psapmon. I have an active HANA Provider set up without issue, as well.

**Comment by kavitha2270** [comment]
@naherring , I am seeing 401 unauthorized error with EnqGetStatistic when it is trying build the connection, can you please make sure that ['MESSAGESERVER/ENQUE"] is reachable. All other web methods(-GetQueueStatistic -ABAPGetWPTable  -GetProcessList) were successfully connected. 
Please run the PS script from your local machine. 
Refer to the link https://github.com/Azure/Azure-Monitor-for-SAP-solutions-preview/wiki/Known-issues-and-Self-Help for more details and you can check the public documentation - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/configure-netweaver-azure-monitor-sap-solutions.

Issue still persists, reach out to cloud support team and they can raise an incident for you.  

Thanks

**Comment by naherring** [comment]
Thank you! It looks like it was the service/protectedwebmethods not being the profile of the Message Server. It was in the DEFAULT.PFL and the App Server profile. I have now successfully added the Provider.
