### ISSUE TITLE
Sap HANA provider failed to deploy with error message "The Operation Failed due to an internal error"

### ISSUE THREAD

**Issue by him-sharma2811** [Azure/Azure-Monitor-for-SAP-solutions-preview#47]
I am getting following message when trying to deploy SAP Hana Provider: 

"{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ProviderInstanceValidationFailed\",\"message\":\\\n      The provider settings validation operation has failed.\\n      Possible Causes: The operation failed due to an internal error.\\n      Recommended Action: Retry the operation.}]}}"

subscriptions: - "c5867f53-93fa-4e22-a423-18f453e1687f"

**Comment by edwardmeade1** [comment]
Hi,

From our analysis it appears that the secret value who have provided may have been deleted. Can you please validate that the correct secret value has been entered in the key vault and is the correct details to connect to you HANA system.

Regards,
Edward

**Comment by him-sharma2811** [comment]
> 

Hi Edward,

Thanks for your response.

I am using database password not secret inside an Azure keyVault.

**Comment by edwardmeade1** [comment]
Hi,

Thanks for the clarification. 

Can you please update the provider with the database password. You can do this by clicking Providers-><<Provider Name>> and a side window should appear. Please re-enter the database password and click update update. 

If the provider is again unsuccessful please update here sharing the error details.

Thanks, 
Edward

**Comment by him-sharma2811** [comment]
Hi Edward,

Yes am still getting same error message after putting correct password.

![SAP Provider Error](https://user-images.githubusercontent.com/55491963/192726313-4f77b060-f5ad-410a-b705-60cb2c72e8c8.JPG)

**Comment by him-sharma2811** [comment]
Hi Edward,

Thanks for your support issue is fixed now, however I would like to understand what was the issue on very first day when it was giving Internal error while deploying it for which I raised this issue. 
Does any changes done in backend after which it start showing  clear message with user name and password error.

Thanks 
Himanshu Sharma
