### ISSUE TITLE
Azure Monitors for SAP - NW provider creation failed.

### ISSUE THREAD

**Issue by yoganandv** [Azure/Azure-Monitor-for-SAP-solutions-preview#7]
We are trying to create SAP NW provider in the AMS (preview) service but the provider fails with below error.
![image](https://user-images.githubusercontent.com/103025384/161699563-57d0d8f2-c5de-4fd1-bff2-99184c6c1eb5.png)

The SAP instance we are trying to connect and the AMS resource we created are on the same VNet but under different subnets. As per Azure, the routing is open by default between the resources which are part of different subnets but within the same VNet, so we do not think that this could be a N/W issue. Could you please check and help with some insights.

Thanks.

Regards,
Yoganand.V

**Comment by M2skills** [comment]
Hi Yoganand, 
It seems the provider addition failed because the host fil entries were not provided,
Below is the format for hostfile entries.

Comma separated hostfile mappings, in case the SAP system is using virtual hostnames, in the format [IP HOSTNAME FQDN]. For example: 192.X.X.X sapservername sapservername.contoso.com,192.X.X.X sapservername2 sapservername2.contoso.com. 

Please use the above format to provider hostfile entries while creating the provider and let us know if there are any issues.

Thanks.

**Comment by yoganandv** [comment]
Hello,

We have set the hostfile entries as per the given syntax but there was no luck, please find the screenshot below.

![image](https://user-images.githubusercontent.com/103025384/161736353-8fbbe03c-6328-4d3d-91d5-2b538c5127ec.png)

Thanks.

**Comment by hsridharan** [comment]
Hi Yoganand,

Request you to try the following recommendation and let us know if you require further assistance : 
1. Application server field - Provide the hostname 'sap33poc' with fqdn e.g sap33poc.contoso.com and not the IP address in the application server field. 
2. Application server field - Needs to be the central instance of the SAP system.
3. Hostfile entries - You would need to provide all the central instance, application server, and replication server (if any) into this box.
In your case, it can be the following. Kindly adjust it according to your SAP configuration.
Format : 192.X.X.X sapservername sapservername.contoso.com,192.X.X.X sapservername2 sapservername2.contoso.com.
**Example:** 
[IP of sap33poc] [sap33poc] sap33poc.contoso.com,  [IP of sap33poccs] [sap33poccs] sap33poccs.contoso.com, [IP of sap33pocers] [sap33pocers] sap33pocers.contoso.com

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsha,

Thanks for the update. Today I have tried as shown below but the try failed with same error, screenshot of the same is also attached to this reply.

FQDN of ASCS instance was provided in the 'Application server' field.
Instance number of ASCS instance, 83
Hostfile entries for ASCS, ERS and PAS was added to the field in the format [IP HOSTNAME FQDN]

![image](https://user-images.githubusercontent.com/103025384/161902055-ec56f9b6-2cd7-45ca-bd9f-1528c868202c.png)

Thanks.

**Comment by hsridharan** [comment]
Hello Yoganand,

Thanks for trying out the recommended steps. After you update the config we are able to call all the SOAP web methods except one which is EnqGetStatistic. Please make sure the profile parameter "service/protectedwebmethods" is set in all the SAP instances by following the steps mentioned in https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/azure-monitor-sap-quickstart#sap-netweaver-provider
To understand the underlying issue can you please run the following PowerShell script and share the screenshot
$SAPHostName = "sap33poccs"
$InstanceNumber = "83"
$Function = " EnqGetStatistic"
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
$sapcntrluri = "https://" + $SAPHostName + ":5" + $InstanceNumber + "14/?wsdl"
$sapcntrl = New-WebServiceProxy -uri $sapcntrluri -namespace WebServiceProxy -class sapcntrl
$FunctionObject = New-Object ($sapcntrl.GetType().NameSpace + ".$Function")
$sapcntrl.$Function($FunctionObject). 
If it still does not resolve the issue, we can schedule a call with you and try to investigate this further.

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsha,

Parameter "service/protectedwebmethods" was set in all Instance profiles like ASCS, ERS, PAS and I can see the below output when I query the parameter via sapcontrol.

![image](https://user-images.githubusercontent.com/103025384/162130292-827e7aae-de17-4fca-bea2-10f4b6db4d42.png)

And coming to the PS script, I did try this couple of days back and it failed and today as well the same error when I tried to get the ABAP workprocess list and Enqueue statistics information, see below the screenshots for both the checks.

ABAP workprocess table check:
![image](https://user-images.githubusercontent.com/103025384/162130531-db5577dc-b5fe-48b3-9057-c56e115bb90e.png)

Enqueue statistics information check:
![image](https://user-images.githubusercontent.com/103025384/162130588-c112903d-ff17-4076-9770-0fc8b166cfc1.png)

Note: I copy/paste the script line by line into PS and command in 6th line of the script fails and hence I did not go further.
6th line in the script: $sapcntrl = New-WebServiceProxy -uri $sapcntrluri -namespace WebServiceProxy -class sapcntrl

Thanks.

**Comment by Darryl-G** [comment]
> Hello Harsha,
> 
> Parameter "service/protectedwebmethods" was set in all Instance profiles like ASCS, ERS, PAS and I can see the below output when I query the parameter via sapcontrol.
> 
> ![image](https://user-images.githubusercontent.com/103025384/162130292-827e7aae-de17-4fca-bea2-10f4b6db4d42.png)
> 
> And coming to the PS script, I did try this couple of days back and it failed and today as well the same error when I tried to get the ABAP workprocess list and Enqueue statistics information, see below the screenshots for both the checks.
> 
> ABAP workprocess table check: ![image](https://user-images.githubusercontent.com/103025384/162130531-db5577dc-b5fe-48b3-9057-c56e115bb90e.png)
> 
> Enqueue statistics information check: ![image](https://user-images.githubusercontent.com/103025384/162130588-c112903d-ff17-4076-9770-0fc8b166cfc1.png)
> 
> Note: I copy/paste the script line by line into PS and command in 6th line of the script fails and hence I did not go further. 6th line in the script: $sapcntrl = New-WebServiceProxy -uri $sapcntrluri -namespace WebServiceProxy -class sapcntrl
> 
> Thanks.

I don't work for MS, but looking at the code there's an assumption that the sapstartsrv (instance agent) has SSL enabled and is listening openly (not locked down to a specific IP address) on TCP port 5##14.

**Comment by yoganandv** [comment]
Hello,

I have checked regarding the port, since 5xx14 is using HTTPS I tried the above command with 5xx13 which uses HTTP, but the results were same. On Networking, the monitoring service and the VM we are trying to monitor are on the same VNet but under different subnet which means the default routing is open, and on top of it the NSG applied at the subnet level has OutBounf rule open for any virtual network so I do not see any issue, and there is no firewall on the VM blocking the port, normally we do not configure local firewall on LINUX VMs where we host SAP instances.

**Comment by Darryl-G** [comment]
Where are you running the PS code from?

**Comment by yoganandv** [comment]
Hello Darryl,

I execute from my laptop after connecting to the subscription under which the SAP instance is hosted. I tried to execute the PS script from a PS on the Azure Portal but it failed with below error. 'New-WebServiceProxy' is not recognized in the PS, and hence I had switched to PS on my work laptop but even here I had to install a module called 'WindowsCompatibility' and only after this the below command with 'New-WebServiceProxy' worked but anyway the connection failed to the remote SAP instance and for that we have this ticket.

$sapcntrl = New-WebServiceProxy -uri $sapcntrluri -namespace WebServiceProxy -class sapcntrl
New-WebServiceProxy: The term 'New-WebServiceProxy' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Looks like the command 'New-WebServiceProxy' is no longer supported in PS, and I found in a MS forum that WindowsCompatibility module can be used to get the command working. Not sure if this is the right way, but there is not much information around on this issue and hence I went ahead with this workaround.

Thanks.

**Comment by Darryl-G** [comment]
I guess you can connect to the required target server instance agent from your laptop?

You can use PS code like this:
`Test-NetConnection -ComputerName "sap33poccs" -Port "58314" -InformationLevel "Detailed"`

**Comment by hsridharan** [comment]
Hello @yoganandv  and @Darryl-G 

Thanks a lot for sharing the screenshot. I see a typo in the Parameter "service/protectedwebmethods" in the image you shared. Profile parameters should be following for EnqGetStatistic, but looks like it is updated as _**EnqGeetStatistic**_

  SDEFAULT -GetQueueStatistic -ABAPGetWPTable -**EnqGetStatistic** -GetProcessList

Request you to try to update the same and 'Restart Service' and re-create the provider.

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsha,

Thanks for pointing out the spelling mistake, my bad. I did not verify the output to the word. After correcting the spelling and restarting the 'sapstartsrv' services for all involved instances I can now get output for the query "ABAPGetWPTable", see screenshot below.

![image](https://user-images.githubusercontent.com/103025384/162383920-65b281da-f58b-40df-a37f-26be5a0334e5.png)

Thanks.

**Comment by yoganandv** [comment]
Hello Darryl,

After correcting the spelling as pointed out by Harsha, I am now able to do a test connection to the remote system using the command you provided, see screenshot below. Thanks for your valuable inputs.

![image](https://user-images.githubusercontent.com/103025384/162384428-c6d2c3bf-a17c-4620-a117-e39912b6222b.png)

Thanks.

**Comment by hsridharan** [comment]
Hello @yoganandv,

Thanks for your response. Is the issue resolved now or are you still facing the issues in creating the provider in AMS? 
If that's the case can you please share the result of the command and share the details. 
/usr/sap/hostctrl/exe/sapcontrol -nr <instance-number> -function GetSystemInstanceList
e.g: /usr/sap/hostctrl/exe/sapcontrol -nr 83 -function GetSystemInstanceList
Please share your email and we can also schedule a call next week to resolve the issue quickly if required.

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsh,

I get the same error while creating SAP NW provider, screenshot below.

![image](https://user-images.githubusercontent.com/103025384/162670405-9174deaf-5c48-4467-8ca4-bbfc222d83d4.png)

Also the output of 'GetSystemInstanceList' is attached below.

![image](https://user-images.githubusercontent.com/103025384/162670425-7bac2456-1861-43ae-8123-047e608a9bd0.png)

SAP AAS 'sap33poca1', 'sap33poca2' and 'sap33poca3' have been shutdown and hence they are marked as GRAY.

Please find my work email ID below, I have back to back meetings today I will be available tomorrow after 11AM IST.

yoganand.vedagiri@skf.com

Thanks.

**Comment by hsridharan** [comment]
Hello Yoganand,

Thanks for your patience here.  We noticed a bug in our system that we are actually checking if all the app servers are up and running prior to making the provider connection successful and we are trying to fix the same asap.
It might take a few days for us to fix the issue and if you would like to expedite the process request you to start these three servers  ["sap33poca1_33", "sap33poca3_33", "sap33poca2_33"] once and try creating the provider in Azure portal. 
You can always shut them down at your convenience once the provider is created successfully. 
Please keep us posted on the outcome of the test.

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsha,

Thanks for the update. I have started the other 3 AAS and then tried to create the NW Provider but it failed with the same issue and the screenshot is shown below.

All 3 AAS up and running:
![image](https://user-images.githubusercontent.com/103025384/162889764-22132fa1-bffa-425f-8fbd-c7b07a9b756c.png)

SAP NW provider error:
![image](https://user-images.githubusercontent.com/103025384/162889819-682af217-5c86-4874-91cf-2e1d50e5942b.png)

Thanks.

**Comment by hsridharan** [comment]
Hello @yoganandv,
Thanks for starting the servers. 
This time looks like we missed the host file entries for "sap33poca2_33", "sap33poca1_33", "sap33poca3_33" servers.
Request you try once by providing all the servers returned by the getsysteminstance list result. 
![image](https://user-images.githubusercontent.com/74435183/163027253-7b3b3b16-fc47-4bf9-bf31-d12d7a6946ce.png)

Please review and fill in the correct IP addresses mentioned below and create another provider with the following host file details.
10.184.128.243 sap33poccs sap33poccs.skf.net,10.184.128.244 sap33pocers sap33pocers.skf.net,10.184.128.248 sap33poc sap33poc.skf.net,ipaddress sap33poca1 sap33poca1.skf.net,ipaddress sap33poca2 sap33poca2.skf.net,ipaddress sap33poca3 sap33poca3.skf.net	
I'll keep a spot in your calendar tomorrow morning (IST) just in case we are still not able to resolve the issue.

Thanks,
Harsha

**Comment by yoganandv** [comment]
Hello Harsha,

After updating the Hostfile entries field with AAS I was able to create the SAP NW provider successfully, also HANA and OS provider was created successfully and the metrics are now collected for all providers and data is now available in the dashboard.

Thanks for your continuous support on this issue, much appreciated.

Regards,
Yoganand.V

**Comment by hsridharan** [comment]
Thanks for updating us @yoganandv. It's great news that we were able to resolve the issues and set up all the providers successfully. Feel free to reach out for any further support required.
